### PR TITLE
Adding SwiftLint

### PR DESCRIPTION
**Pull request by bladebunny**
- Adds initial SwiftLint implementation -- note that contributors will need to install it locally
- Added initial rules file (.swift-lint.yml) and turned down some basic thresholds -- can always be adjusted
- Fixed warnings where possible that I could fix without introducing regressions
- Added README entry for SwiftLint

### CODE REVIEW

**Comment by PranjalDev** [comment]
@bladebunny Are you planning to add this to GitHub actions as well if not can I pick that up ?

**Comment by bladebunny** [comment]
@PranjalDev Are you thinking to lint on a PR?  I already enable lint on build by adding a pre-compile script/phase to the project.  Not planning to add lint on PR as I don't believe I have access/permission for that.  I'm happy to do it, if possible, or for someone else to do it - either way is good.  But perhaps a new issue/feature for that?

**Comment by PranjalDev** [comment]
> @PranjalDev Are you thinking to lint on a PR? I already enable lint on build by adding a pre-compile script/phase to the project. Not planning to add lint on PR as I don't believe I have access/permission for that. I'm happy to do it, if possible, or for someone else to do it - either way is good. But perhaps a new issue/feature for that?

Yes it is possible,
We just need to create an GitHub action file for this, somebody already create one CI for build, we can add one more job for lint, which will add linting comments in the PR itself.

I have already integrated it on my fork check out the comments in the job:
https://github.com/PranjalDev/VocabularyTraining/pull/1/files

**Comment by bladebunny** [comment]
@PranjalDev I see.  Let me just add to my PR.  And then we add/enable the action via the Github dashboard?

**Comment by PranjalDev** [comment]
Please check the latest changes:
https://github.com/PranjalDev/VocabularyTraining/pull/1/files
https://github.com/PranjalDev/VocabularyTraining/actions/runs/3332132882

Also generated a separate PR for this if needed as reference: https://github.com/misteu/VocabularyTraining/pull/30

**Comment by bladebunny** [comment]
The last merge borked my PR -- need to re-apply the warning fixes for LanguageScreenViewController now.  I'll make the fixes but would appreciate if it could be accepted so this doesn't keep happening.  Thx.

**Comment by misteu** [comment]
> Please check the latest changes: https://github.com/PranjalDev/VocabularyTraining/pull/1/files https://github.com/PranjalDev/VocabularyTraining/actions/runs/3332132882
> 
> Also generated a separate PR for this if needed as reference: #30

Now all the needed changes for the github actions are on this branch as well, right?

> The last merge borked my PR -- need to re-apply the warning fixes for LanguageScreenViewController now. I'll make the fixes but would appreciate if it could be accepted so this doesn't keep happening. Thx.

Oh sorry, my bad :(

Wasn't really aware of that. I just started reviewing them chronologically. Will merge yours soon!

**Comment by bladebunny** [comment]
@misteu No worries.  All fixed and merged.  It has @PranjalDev's swift lint action (thx @PranjalDev).  I'm not sure if it triggers automatically or it requires config on dashboard.  Looking at that now.

**Comment by bladebunny** [comment]
Looks like Lint does run automatically.  You could just merge @PranjalDev's too so he can get credit.  Should be no conflicts.

**Comment by misteu** [comment]
> @misteu No worries. All fixed and merged. It has @PranjalDev's swift lint action (thx @PranjalDev). I'm not sure if it triggers automatically or it requires config on dashboard. Looking at that now.

Looks like it's in place automagically :) just started the pipeline again: 
grafik

It only seems to need the maintainer's approval for first time contributors. After that it will probably start automatically.

**Comment by bladebunny** [comment]
One thing, it looks likes it not using the same rules -- may be some rules associated with that plugin, but probably not a big deal.  The rules I'm using on Xcode build are slightly more aggressive but also pass currently.

**Comment by misteu** [comment]
I'll check again tomorrow as I'm not on my machine anymore.

Actually I think it's fine having rather aggressive rules.

However, I saw that there are like 300-something warnings when leading whitespace is enabled.

I might activate this one later again and fix all of these. So that no-one else has to fight with these.

For now it looks great. Thanks! Will merge this tomorrow

**Comment by bladebunny** [comment]
@misteu Yeah, that leading whitespace rule is pretty useless.  We also disable it in my jobby-job.  The thing is, is doesn't just detect spaces -- so if you remove spaces, it'll still trigger on returns.  Not sure why you'd use it.

I did some more research and was able to figure out how to set it to use the local lint rules.  Basically you add a --config with path to the rules.  Unfortunately, not clear if that's relative to the action yml or the git root or what.  I update the PR with the relative path from the action yml -- hopefully that'll work.  I was not able to run the action to test but should be pretty straightforward.  Here's a link to the swift lint plugin issue that discusses it:
https://github.com/norio-nomura/action-swiftlint/issues/19

**Pull request merged**
